# [Fungsi Skalar Matematika - ABS()](https://academy.dqlab.id/main/livecode/171/336/1606?pr=0)

In [ ]:
SELECT StudentID, FirstName, LastName, Semester1, Semester2, ABS(MarkGrowth) AS MarkGrowth
FROM students;

# [Fungsi Skalar Matematika - CEILING()](https://academy.dqlab.id/main/livecode/171/336/1607?pr=0)

In [ ]:
SELECT StudentID, FirstName, LastName, CEILING(Semester1) AS Semester1, CEILING(Semester2) AS Semester2,MarkGrowth
FROM students;

# [Fungsi Skalar Matematika - FLOOR()](https://academy.dqlab.id/main/livecode/171/336/1608?pr=0)

In [ ]:
SELECT StudentID, FirstName, LastName, FLOOR(Semester1) AS Semester1, FLOOR(Semester2) AS Semester2, MarkGrowth
FROM students;

# [Fungsi Skalar Matematika - ROUND()](https://academy.dqlab.id/main/livecode/171/336/1609?pr=0)

In [ ]:
SELECT StudentID, FirstName, LastName, ROUND(Semester1,1) AS Semester1, ROUND(Semester2,0) AS Semester2, MarkGrowth
FROM students;

# [Fungsi Skalar Matematika - SQRT( )](https://academy.dqlab.id/main/livecode/171/336/1610?pr=0)

In [ ]:
SELECT StudentID, FirstName, LastName, SQRT(Semester1) AS Semester1, Semester2, MarkGrowth
FROM students;

# [Tugas Praktek-1.1](https://academy.dqlab.id/main/livecode/171/336/1611?pr=0)

In [ ]:
SELECT StudentID, FirstName, LastName, MOD(Semester1,2) AS Semester1 , Semester2, EXP(MarkGrowth) FROM students;

# [Fungsi Text - CONCAT( )](https://academy.dqlab.id/main/livecode/171/337/1613?pr=0)

In [ ]:
SELECT StudentID, CONCAT(FirstName, LastName) AS Name, Semester1, Semester2, MarkGrowth  
FROM students;

# [Fungsi Text - SUBSTRING_INDEX( )](https://academy.dqlab.id/main/livecode/171/337/1634?pr=0)

In [ ]:
SELECT StudentID, SUBSTRING_INDEX(Email, '@', 1) AS Name
FROM students;

# [Fungsi Text - SUBSTR( )](https://academy.dqlab.id/main/livecode/171/337/1635?pr=0)

In [ ]:
SELECT StudentID, SUBSTR(FirstName, 2, 3) AS Initial 
FROM students;

# [Fungsi Text - LENGTH( )](https://academy.dqlab.id/main/livecode/171/337/1636?pr=0)

In [ ]:
SELECT StudentID, FirstName, LENGTH(FirstName) AS Total_Char
FROM students;

# [Fungsi Text - REPLACE( )](https://academy.dqlab.id/main/livecode/171/337/1637?pr=0)

In [ ]:
SELECT StudentID, Email, REPLACE(Email,'yahoo', 'gmail') AS New_Email
FROM students;

# [Tugas Praktek-2.1](https://academy.dqlab.id/main/livecode/171/337/1638?pr=0)

In [ ]:
SELECT StudentID, UPPER(FirstName) AS FirstName, LOWER(LastName) AS LastName FROM students;

# [Fungsi Aggregate - SUM()](https://academy.dqlab.id/main/livecode/171/340/1640?pr=null)

In [ ]:
SELECT SUM(Semester1) AS Total_1, SUM(Semester2) AS Total_2
FROM students;

# [Fungsi Aggregate - COUNT()](https://academy.dqlab.id/main/livecode/171/340/1641?pr=null)

In [ ]:
SELECT COUNT(FirstName) AS Total_Student 
FROM students;

# [Fungsi Aggregate - AVG( )](https://academy.dqlab.id/main/livecode/171/340/1642?pr=null)

In [ ]:
SELECT AVG(Semester1) AS AVG_1, AVG(Semester2) AS AVG_2 
FROM students;

# [Tugas Praktek-3.1](https://academy.dqlab.id/main/livecode/171/340/1643?pr=null)

In [ ]:
SELECT MIN(Semester1) AS Min1, MAX(Semester1) AS Max1,MIN(Semester2) AS Min2, MAX(Semester2) AS Max2
FROM students;

# [Group by Single Column](https://academy.dqlab.id/main/livecode/171/340/1645?pr=null)

In [ ]:
SELECT province,
COUNT(DISTINCT order_id) AS total_order,
SUM(item_price) AS total_price
FROM sales_retail_2019
GROUP BY province;

# [Group by Multiple Column](https://academy.dqlab.id/main/livecode/171/340/1646?pr=null)

In [ ]:
SELECT province,brand,
COUNT(DISTINCT order_id) AS total_order,
SUM(Item_price) AS total_price FROM sales_retail_2019
GROUP BY province, brand;

# [Fungsi Aggregate dengan Grouping](https://academy.dqlab.id/main/livecode/171/340/1647?pr=null)

In [ ]:
SELECT province, 
COUNT(DISTINCT order_id) AS total_unique_order,
SUM(item_price) AS revenue 
FROM sales_retail_2019
GROUP BY province;

# [Tugas Praktek-3.2](https://academy.dqlab.id/main/livecode/171/340/1650?pr=null)

In [ ]:
SELECT MONTH(order_date) AS order_month, SUM(item_price) AS total_price, 
CASE  
    WHEN SUM(item_price) >= 30000000000 THEN 'Target Achieved'
    WHEN SUM(item_price) <= 25000000000 THEN 'Less Performed'
    ELSE 'Follow Up'
END as remark
FROM sales_retail_2019
GROUP BY MONTH(order_date);

# [Proyek Pekerjaan - Analisis Penjualan Part 1](https://academy.dqlab.id/main/livecode/171/341/1652?pr=null)

In [ ]:
-- 1. Total jumlah seluruh penjualan (total/revenue).
SELECT SUM(total) as total 
FROM tr_penjualan;
-- 2. Total quantity seluruh produk yang terjual.
SELECT SUM(qty) as qty 
FROM tr_penjualan;
-- 3. Total quantity dan total revenue untuk setiap kode produk.
SELECT kode_produk, SUM(qty) as qty, SUM(total) as total 
FROM tr_penjualan
GROUP BY kode_produk;

# [Proyek Pekerjaan - Analisis Penjualan Part 2](https://academy.dqlab.id/main/livecode/171/341/1654?pr=null)

In [ ]:
-- 4. Rata - Rata total belanja per kode pelanggan.
SELECT kode_pelanggan, AVG(total) AS avg_total 
FROM tr_penjualan
GROUP BY kode_pelanggan;
/* 5. Selain itu,  jangan lupa untuk menambahkan kolom baru 
dengan nama ‘kategori’ yang mengkategorikan total/revenue ke dalam 
3 kategori: High: > 300K; Medium: 100K - 300K; Low: <100K. */
SELECT kode_transaksi,kode_pelanggan,no_urut,kode_produk,nama_produk,qty,total,
CASE  
    WHEN total > 300000 THEN 'High'
    WHEN total < 100000 THEN 'Low'   
    ELSE 'Medium'  
END as kategori 
FROM tr_penjualan;